name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 4.0.0
homepage: https://github.com/p-Osteen/Flare-Flutter

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: "3.9.2"
